# Generated by Django 5.0.6 on 2024-05-28 01:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='ratings',
            field=models.ManyToManyField(related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
