# Generated by Django 5.0.6 on 2024-05-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_attempt_rating_attempt_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
