# Generated by Django 5.0.6 on 2024-05-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_alter_attempt_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='sheet_url',
            field=models.URLField(default=None),
        ),
    ]
