# Generated by Django 5.0.4 on 2024-04-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='listings',
        ),
        migrations.AddField(
            model_name='bids',
            name='listings',
            field=models.ManyToManyField(related_name='bids', to='auctions.listings'),
        ),
    ]
