# Generated by Django 5.0.4 on 2024-04-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_bids_listings_bids_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='listings',
        ),
        migrations.AddField(
            model_name='listings',
            name='bids',
            field=models.ManyToManyField(related_name='listings_bids', to='auctions.bids'),
        ),
    ]
