# Generated by Django 5.0.4 on 2024-04-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_bids_listings_listings_bids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='bids',
        ),
        migrations.AddField(
            model_name='bids',
            name='listings',
            field=models.ManyToManyField(related_name='bids', to='auctions.listings'),
        ),
    ]
