# Generated by Django 5.0.4 on 2024-04-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_categories_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='is_closed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
