# Generated by Django 5.0.4 on 2024-04-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listings_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='listings',
        ),
        migrations.AddField(
            model_name='comment',
            name='listings',
            field=models.ManyToManyField(related_name='comments', to='auctions.listings'),
        ),
    ]
